### ISSUE TITLE
Are tags still being maintained?

### ISSUE THREAD

**Issue by adamv** [trevor/ImageMagick#1]
Are tags still being maintained, and if so, what's the current latest version?

Probably worthwhile to update the associated Homebrew formula.

If you are no longer maintaining this, let me know.

**Comment by trevor** [comment]
@mxcl and i discussed this briefly on 2011-9-14, the decision was to think on it. happy to update tags if i have a SVN ref to correlate too.

here was my initial reply:

<blockquote>
i hadn't received any notice as to what revision to use. as discussed on the mailing list this is particularly difficult since the revision isn't tagged for the release (no tags directory):
https://www.imagemagick.org/subversion/ImageMagick/

it appears these lines were removed (which i had updated to point towards myself):
https://github.com/mxcl/homebrew/blob/4e7c332a483b339b9db60ab0577176bfbcb197b7/Library/Formula/imagemagick.rb#L32-33

how often would you prefer that i manually take a look at this?
</blockquote>


essentially the tarball release does not correlate 1:1 / file-to-file to any SVN revision, so we have to manually make a best approximation.
